<?php

function nginx_aggregation_settings_form() {

  /* $form['bandwidth_optimizations']['nginx_aggregation_css'] = array( */
  /*   '#type' => 'checkbox', */
  /*   '#title' => t('@nginx_http_concat_module CSS aggregation.', array('@nginx_http_concat_module' => l('Nginx HTTP Concat', URI_NGINX_HTTP_CONCAT))), */
  /*   '#description' => t('Use @nginx_http_concat_module for aggregating CSS files. Circumvents all core aggregation.', array('@nginx_http_concat_module' => l('Nginx HTTP Concat', URI_NGINX_HTTP_CONCAT))), */
  /*   '#default_value' => variable_get('nginx_aggregation_css', 0), */
  /*   'weight' => 1, */
  /* ); */
  /* $form['bandwidth_optimizations']['nginx_aggregation_js'] = array( */
  /*   '#type' => 'checkbox', */
  /*   '#title' => t('@nginx_http_concat_module JS aggregation.', array('@nginx_http_concat_module' => l('Nginx HTTP Concat', URI_NGINX_HTTP_CONCAT))), */
  /*   '#description' => t('Use @nginx_http_concat_module for aggregating JS files. Circumvents all core aggregation.', array('@nginx_http_concat_module' => l('Nginx HTTP Concat', URI_NGINX_HTTP_CONCAT))), */
  /*   '#default_value' => variable_get('nginx_aggregation_js', 0), */
  /*   'weight' => 1, */
  /* ); */

} // nginx_aggregation_settings_form